In [29]:
from src.Spinor import *

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [30]:
s = Spinor([3,1], [1/np.sqrt(2),0,0,1/np.sqrt(2)], [0,0,0,0])

In [31]:
s.to_column()
s.column_to_spinor(s.evects)

[[ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j]
 [ 0.        +0.j  1.41421356+0.j  0.        +0.j  1.41421356+0.j]
 [ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j]
 [ 0.        +0.j -1.41421356+0.j  0.        +0.j -1.41421356+0.j]]


c:\Users\toonh\Documents\Courses\Master Thesis\Spinors\Spinor\src\Spinor.py:95: RuntimeWarning: divide by zero encountered in divide
  return evects
c:\Users\toonh\Documents\Courses\Master Thesis\Spinors\Spinor\src\Spinor.py:95: RuntimeWarning: invalid value encountered in divide
  return evects


(nan+nanj) + ((nan+nanj)^g0) + ((nan+nanj)^g1) + ((nan+nanj)^g2) + ((nan+nanj)^g3) + ((nan+nanj)^g01) + ((nan+nanj)^g02) + ((nan+nanj)^g03) + ((nan+nanj)^g12) + ((nan+nanj)^g13) + ((nan+nanj)^g23) + ((nan+nanj)^g012) + ((nan+nanj)^g013) + ((nan+nanj)^g023) + ((nan+nanj)^g123) + ((nan+nanj)^g0123)

In [32]:
s.evects.round(3)

array([[-0.   +0.j   ,    inf  +nanj,    nan  +nanj,  0.   +0.j   ],
       [-0.   +0.271j,    nan  +nanj,    nan  +nanj, -0.653+0.j   ],
       [ 0.   +0.j   ,    nan  +nanj,    inf  +nanj,  0.   +0.j   ],
       [ 0.   +0.653j,    nan  +nanj,    nan  +nanj,  0.271+0.j   ]])

In [37]:
np.dot(s.evects,np.conj(s.evects.T))

array([[nan+nanj, nan+nanj, nan+nanj, nan+nanj],
       [nan+nanj, nan+nanj, nan+nanj, nan+nanj],
       [nan+nanj, nan+nanj, nan+nanj, nan+nanj],
       [nan+nanj, nan+nanj, nan+nanj, nan+nanj]])

In [43]:
v1 = s.evects[:,0]
v2 = s.evects[:,3]

In [49]:
np.outer(v1,np.conj(v1)) + np.outer(v2,np.conj(v2))

array([[ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j],
       [ 0.        +0.j,  0.35355339-0.j, -0.        +0.j,
        -0.35355339+0.j],
       [ 0.        +0.j, -0.        +0.j,  0.        +0.j,
         0.        +0.j],
       [ 0.        +0.j, -0.35355339+0.j,  0.        +0.j,
        -0.35355339+0.j]])