In [130]:
from src.Spinor import *

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [131]:
s = Spinor([3,1], [1/np.sqrt(2),0,0,1/np.sqrt(2)], [0,0,0,0])

In [133]:
s.to_column()
s.column_to_spinor(s.evects[:,0])

[(-0.7071067811865475+0j), 0j, 0j, 0j]


-((0.70711-0j)^g0)

In [145]:
sum = 0
for i,e in enumerate(s.evects):
    sum += np.outer(e.real,e.real)*s.evals[i]
    print(sum)

[[-0.14644661  0.          0.         -0.35355339]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.35355339  0.          0.         -0.85355339]]
[[-0.14644661  0.          0.         -0.35355339]
 [ 0.         -0.14644661  0.35355339  0.        ]
 [ 0.          0.35355339 -0.85355339  0.        ]
 [-0.35355339  0.          0.         -0.85355339]]
[[ 0.70710678  0.          0.         -0.70710678]
 [ 0.         -0.14644661  0.35355339  0.        ]
 [ 0.          0.35355339 -0.85355339  0.        ]
 [-0.70710678  0.          0.         -0.70710678]]
[[ 0.70710678  0.          0.         -0.70710678]
 [ 0.          0.70710678  0.70710678  0.        ]
 [ 0.          0.70710678 -0.70710678  0.        ]
 [-0.70710678  0.          0.         -0.70710678]]
